global class GSP_TriggerContext
{
	global static boolean DisableAllTriggers =				false;
	global static boolean DisableQuoteLineItemTriggers =	false;
	global static boolean DisableOpportunityTriggers =		false;
	global static boolean DisableAccountTriggers =			false;
	global static boolean DisableQuoteTriggers =			false;
	global static boolean DisableContactTriggers =			false;
	global static boolean DisableLeadTriggers =				false;
	global static boolean DisableEventTriggers =			false;
	global static boolean DisableCreditNoteTriggers =		false;
	global static boolean DisableInvoiceTriggers =			false;
}